### ISSUE TITLE
ajax.googleapis.com loads as insecure content

### ISSUE THREAD

**Issue by artfulbodger** [spenmath/ScoutsEMSIssues#113]
Mixed Content: The page at 'https://dashboard.scouts-ems.org.uk/registrationsGroup.php' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js'. This content should also be served over HTTPS.

Suggest updating to use https ?

**Comment by spenmath** [comment]
I'm not sure this is a thing any more. I can't find that google code anywhere!
